#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""commands/draft — moved from _legacy.py (batch)."""
from __future__ import annotations
import sys, re
from pathlib import Path
try:
    from shelf_core.playlists import *
    from shelf_core.transcript import *
    from shelf_core.notes import *
    from shelf_core.notes import _scanned_region  # underscore not exported by *
    from shelf_core.citation import *
    from shelf_core.match import tokens, subseq
    from shelf_core.config import ROOT, REF
    from shelf_core.citation import *
except ImportError:
    from playlists import *  # type: ignore
    from transcript import *  # type: ignore
    from notes import *  # type: ignore
    try:
        from notes import _scanned_region  # type: ignore
    except ImportError:
        pass
    from citation import *  # type: ignore
    from match import tokens, subseq  # type: ignore
    from config import ROOT, REF  # type: ignore
def cmd_draft(argv):
    if not argv:
        sys.exit("usage: draft KEY")
    slug, ident = parse_session_key(argv[0])
    key = session_key_of(slug, ident)
    note = find_note(key)
    if note is None:
        sys.exit(f"No note for session {key} — run `scaffold {key}` first")
    txt = note.read_text(encoding="utf-8")
    rec = get_session(key)
    tm = TITLE_ROW_RE.search(txt)
    title = tm.group(1).strip() if tm else (rec["title"] if rec else key)
    block = rec["block"] if rec else ""
    src_rel = rec["rel"] if rec else ""
    defs = _parse_note_definitions(txt)
    papers = _parse_note_papers(txt)
    dd = "\n".join(
        f'<dt>{d["term"]} <span class="tag">verbatim</span></dt>\n'
        f'<dd>"{d["quote"]}" <span class="cite">{d["cite"]}</span></dd>'
        for d in defs)
    if dd:
        defs_section = ('<h2 id="definitions">Definitions and coined terms</h2>\n'
                        f'<dl class="ref">\n{dd}\n</dl>')
    else:
        defs_section = ('<h2 id="definitions">Definitions and coined terms</h2>\n'
                        '<p>No definitions distilled in this session yet — carry '
                        'them over from the note.</p>')
    papers_lis = "\n".join(f"    <li>{p}</li>" for p in papers) or \
        "    <li>None yet.</li>"
    html = f"""<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} — {PLAYLIST_NAMES[slug]} shelf</title>
<link rel="stylesheet" href="{{{{ASSET_PREFIX}}}}/lesson.css">
</head>
<body>
<main>
<header class="lesson-head">
  <p class="kicker">{block} — {PLAYLIST_NAMES[slug]}</p>
  <h1>{title}</h1>
  <p class="meta">Source: <code>{src_rel}</code> • Session {key} • Last reviewed: YYYY-MM-DD</p>
</header>

<div class="callout">
  <h3>Document status: draft — unreviewed</h3>
  <p>Generated by <code>python3 tools/shelf.py draft {key}</code> from
  <code>{os_rel(note, ROOT)}</code>. Quotes are verbatim with minute cites.
  Complete the placeholder sections, then verify with
  <code>python3 tools/shelf.py check</code>.</p>
</div>

{defs_section}

<h2 id="themes">Themes</h2>
<p>Digests from the session note; every verbatim claim keeps its cite.
<span class="cite">({key}, MM:SS)</span></p>

<section class="recap">
  <h2>Recap</h2>
  <ul><li>…</li></ul>
</section>

<section class="next">
  <h2>What next</h2>
  <p>… <span class="cite">(KEY, MM:SS)</span></p>
</section>

<h2 id="quiz">Self-check</h2>
<!-- Repeat per question with increasing radio name="q1", q2 … data-answer =
     the correct option number; at least three options. -->
<details class="quiz" data-answer="1" data-explain="…">
  <summary>Question</summary>
  <div class="quiz-body">
    <p class="quiz-prompt">…</p>
    <ul class="quiz-options">
      <li><label><input type="radio" name="q1" value="1"> …</label></li>
      <li><label><input type="radio" name="q1" value="2"> …</label></li>
      <li><label><input type="radio" name="q1" value="3"> …</label></li>
    </ul>
    <p class="quiz-feedback"></p>
    <div class="quiz-reveal"></div>
  </div>
</details>

<section class="cite">
  <h2>Sources</h2>
  <ol>
    <li>Session {key} — "{title}". Transcript: <code>{src_rel}</code></li>
    <li>Session note: <code>{os_rel(note, ROOT)}</code></li>
  </ol>
</section>

<footer class="lesson-foot">
  <p class="lang-switch">{PLAYLIST_NAMES[slug]} shelf • English edition • LTR</p>
  <p>Last reviewed: YYYY-MM-DD • Status: draft awaiting review</p>
</footer>
</main>
<script src="{{{{ASSET_PREFIX}}}}/lesson.js"></script>
</body>
</html>
"""
    dest = docs_dir(slug)
    dest.mkdir(parents=True, exist_ok=True)
    out = dest / note.name.replace(".md", ".html")
    if out.exists():
        sys.exit(f"Already exists: {os_rel(out, ROOT)}")
    html = (html.replace("{{ASSET_PREFIX}}", _asset_prefix(dest)))
    # Papers section goes before Sources (informational, not gate-enforced).
    papers_section = (f'<h2 id="papers">Papers cited</h2>\n<ul>\n{papers_lis}\n</ul>\n\n'
                      '<section class="cite">')
    html = html.replace('<section class="cite">', papers_section, 1)
    out.write_text(html, encoding="utf-8")
    print(f"Draft -> {os_rel(out, ROOT)} "
          f"({len(defs)} definition(s) wired with quotes+cites, {len(papers)} paper(s) listed)")


def doc_idents(doc: Path):
    return [f"{int(x):03d}" for x in re.findall(r"(?<!\d)(\d{3})(?!\d)", doc.name)]


def doc_in_scope(doc: Path, pl: str, scope) -> bool:
    if scope is None:
        return True
    if scope[0] == "playlist":
        return pl == scope[1]
    if scope[0] == "range":
        _, lo, hi = scope
        return pl == DEFAULT_PLAYLIST and any(
            lo <= int(x) <= hi for x in doc_idents(doc))
    if scope[0] == "sess":
        _, slug, ident = scope
        if pl != slug:
            return False
        if pl == "ex":
            return True   # extras docs carry no numbers; scope by playlist
        return ident in doc_idents(doc)
    if scope[0] == "block":
        _, name, slug_b = scope
        if pl != slug_b:
            return False
        return any(block_of(int(x), slug_b) == name for x in doc_idents(doc))
    return False


def note_in_scope(pl: str, ident: str, scope) -> bool:
    if scope is None:
        return True
    if scope[0] == "playlist":
        return pl == scope[1]
    if scope[0] == "sess":
        return pl == scope[1] and ident == scope[2]
    if scope[0] == "range":
        _, lo, hi = scope
        return pl == DEFAULT_PLAYLIST and ident.isdigit() and lo <= int(ident) <= hi
    if scope[0] == "block":
        _, name, slug_b = scope
        return (pl == slug_b and ident.isdigit()
                and block_of(int(ident), slug_b) == name)
    return False


def check_doc(doc: Path, pl: str, fails: list, verbose=True):
    html_txt = doc.read_text(encoding="utf-8", errors="replace")
    records = scan_html(html_txt)
    srcs = {}

    def src_for(key):
        if key not in srcs:
            srcs[key] = CleanSource(key) if get_session(key) else None
        return srcs[key]

    for rec in records:
        qt = tokens(rec["quote"])
        if len(qt) < QUOTE_MIN_TOKENS:
            continue
        if not rec["cited"]:
            msg = (f'{doc.name}: uncited quote ({len(qt)} tokens, no same-line '
                   f'cite): "{rec["quote"][:60]}"')
            print(f"  ⚠ {msg}")
            fails.append(msg)
            continue
        src = src_for(rec["key"])
        if src is None or src.rec is None:
            msg = (f'{doc.name}: cite ({rec["key"]}) resolves to no session in '
                   f"the corpus")
            print(f"  ✗ {msg}")
            fails.append(msg)
            continue
        verdict, vmsg = check_quote(src, rec["quote"], rec["secs"],
                                    doc.name, rec["key"])
        if verdict is None:
            continue
        disp = rec["quote"] if len(rec["quote"]) <= 40 else rec["quote"][:37] + "…"
        if verdict == "OK":
            if verbose:
                print(f'  ✓ "{disp}" {fmt_cite(rec["key"], rec["secs"])}')
            continue
        print(f'  ✗ "{disp}" {fmt_cite(rec["key"], rec["secs"])} — {vmsg}')
        hint = source_hint(rec["key"], qt,
                           near=(rec["secs"][0] if rec["secs"] else None))
        if hint:
            label, span, minute = hint
            shown = span if len(span) <= 160 else span[:157] + "…"
            print(f'      {label} @{fmt_mmss(minute)} (copy-paste this): "{shown}"')
        fails.append(f'{doc.name}: "{disp}" — {vmsg}')
    # links & anchors resolve relative to the doc itself (any depth)
    ids = set(re.findall(r'id="([^"]+)"', html_txt))
    ids |= set(re.findall(r'<a\s[^>]*name="([^"]+)"', html_txt))
    for m in re.finditer(r'(href|src)="([^"]+)"', html_txt):
        url = m.group(2)
        if url.startswith(("http://", "https://", "mailto:", "data:")):
            continue
        if url.startswith("#"):
            frag = url[1:]
            if frag and frag not in ids:
                msg = f"{doc.name}: broken anchor #{frag}"
                print(f"  ✗ {msg}")
                fails.append(msg)
            continue
        target = (doc.parent / url.split("#")[0]).resolve()
        if not target.exists():
            msg = f"{doc.name}: broken link -> {url}"
            print(f"  ✗ {msg}")
            fails.append(msg)
    if "\ufffd" in html_txt:
        msg = (f"{doc.name}: contains U+FFFD replacement character — fix from the "
               f"source (tokens silently shatter)")
        print(f"  ✗ {msg}")
        fails.append(msg)


def check_note(note: Path, fails: list, verbose=True):
    txt = note.read_text(encoding="utf-8")
    name = note.name
    # Config-driven metadata labels (corpus.note_meta), diacritic-tolerant.
    st = meta_status(txt)
    if st is None:
        msg = f"{name}: no | {STATUS_LABEL} | row in Metadata"
        print(f"  ✗ {msg}")
        fails.append(msg)
    elif not status_is_valid(st):
        msg = (f"{name}: invalid {STATUS_LABEL} '{st.strip()}' — expected one "
               f"of {' / '.join(STATUS_VALUES)}")
        print(f"  ✗ {msg}")
        fails.append(msg)
    fl = meta_flags(txt)
    if fl is None:
        msg = f"{name}: no | {FLAGS_LABEL} | row in Metadata"
        print(f"  ✗ {msg}")
        fails.append(msg)
    elif not flags_is_valid(fl):
        msg = (f"{name}: invalid {FLAGS_LABEL} '{fl.strip()}' — expected "
               f"'{FLAGS_NO}' or '{FLAGS_YES}…'")
        print(f"  ✗ {msg}")
        fails.append(msg)
    emp = note_is_empty(note)
    if emp:
        msg = f"{name}: {emp}"
        print(f"  ✗ {msg}")
        fails.append(msg)
    if "\ufffd" in _scanned_region(txt):
        msg = (f"{name}: U+FFFD replacement character in the scanned region — "
               f"tokens silently shatter; fix the word from the source")
        print(f"  ✗ {msg}")
        fails.append(msg)
    sess_key = note_source_key(txt, note)
    if sess_key is None:
        msg = (f"{name}: cannot resolve session key (fill | Session | or rename "
               f"to cs-NNN-/rr-NNN-/ex-slug- form)")
        print(f"  ✗ {msg}")
        fails.append(msg)
        return
    src = CleanSource(sess_key)
    if src.rec is None:
        msg = f"{name}: transcript file missing for {sess_key}"
        print(f"  ✗ {msg}")
        fails.append(msg)
        return
    records = scan_lines(txt)
    rep = report_records(records, src, sess_key, name, verbose=verbose)
    # Verbatim gate — evidence lane only: minute mismatch / not-found, and a
    # blockquote ("> «»") quote with no cite. Digest-prose «» stay advisory
    # (rep["soft"]) so stylistic quoting in خلاصة text can't red-flag a note.
    fails.extend(rep["fails"])


def playlist_docs():
    docs = []
    for pl in playlist_keys():
        d = docs_dir(pl)
        if d.is_dir():
            docs += [(p, pl) for p in sorted(d.glob("*.html"))]
    t = topics_dir()
    if t.is_dir():
        docs += [(p, "topics") for p in sorted(t.glob("*.html"))]
    return docs


def parse_scope(arg: str):
    """Scope argument -> scope tuple. A path to an existing .md/.html file is a
    direct single-file scope (used by fixtures and targeted re-checks)."""
    p = Path(arg)
    if ("/" in arg or arg.endswith((".md", ".html"))) and p.exists():
        return ("file", p)
    if arg in playlist_keys():
        return ("playlist", arg)
    m = re.fullmatch(rf"({numeric_slugs()})-(\d{{1,3}})", arg)
    if m:
        return ("sess", m.group(1), f"{int(m.group(2)):03d}")
    m = re.fullmatch(r"ex-([a-z0-9-]+)", arg)
    if m:
        return ("sess", "ex", m.group(1))
    m = re.fullmatch(r"(\d{1,3})", arg)
    if m:
        return ("sess", DEFAULT_PLAYLIST, f"{int(m.group(1)):03d}")
    m = re.fullmatch(r"(\d{1,3})\s*[-–—]\s*(\d{1,3})", arg)
    if m:
        return ("range", int(m.group(1)), int(m.group(2)))
    for pl in playlist_keys():
        for (_, _), name in BLOCKS.get(pl, []):
            if arg == name:
                return ("block", name, pl)
    valid = ("nothing (= all) | a playlist (" + " / ".join(playlist_keys()) +
             ") | a block name | KEY (<slug>-NNN, ex-<slug>, bare NNN = cs) | "
             "A-B (applies to cs) | a path to one .md/.html file")
    sys.exit(f"Unknown check scope: {arg!r}\nValid scopes: {valid}")


