#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""commands/inventory — moved from _legacy.py (batch helpers now in helpers.py)."""

from __future__ import annotations

import sys
from pathlib import Path

# H2.2: flat-layout fallback removed — the package is always a package.
from shelf_core.playlists import PLAYLIST_NAMES, PLAYLIST_DIRS, DUPLICATE_SESSIONS, load_sessions
from shelf_core.notes import find_note, note_status_of, _cell, STATUS_LABEL
from shelf_core.config import INVENTORY


def cmd_inventory(argv=None):
    # T7.1: --out redirects the write (selftest regenerates inventory INSIDE
    # its fixture corpus; the project's own inventory.md stays untouched).
    out = INVENTORY
    if argv:
        for i, a in enumerate(argv):
            if a == "--out" and i + 1 < len(argv):
                out = Path(argv[i + 1])
    sessions = load_sessions()
    lines = ["# Shelf inventory (generated — do not hand-edit)", "",
             # P6.10: the header names the CONFIGURED status label (was the
             # hardcoded '| Status |' — wrong on a shelf with note_meta.status_label)
             f"> Generated by `python3 tools/shelf.py inventory`. "
             f"Note status reads `| {STATUS_LABEL} |` from `reference/<playlist>/notes/`.", ""]
    total_missing = 0
    counts = {}
    # Which playlists to render used to be a literal triple naming another shelf's playlists, so
    # a shelf whose real playlists are is-/ts- emitted no rows for either of them while still
    # reporting "Total: 58 sessions", and its Counts line was three zeroes of nothing. Derive the
    # list from what is actually indexed, keeping PLAYLIST_DIRS order and appending surprises.
    _present = {s["pl"] for s in sessions}
    PLS = [q for q in PLAYLIST_DIRS if q in _present] + sorted(_present - set(PLAYLIST_DIRS))
    for pl in PLS:
        subs = [s for s in sessions if s["pl"] == pl]
        missing = 0
        lines.append(f"## {pl} — {PLAYLIST_NAMES.get(pl, pl)}")
        lines.append("")
        lines.append("| Session | Title | Block | Note status |")
        lines.append("| --- | --- | --- | --- |")
        for s in subs:
            note = find_note(s["key"])
            if s["key"] in DUPLICATE_SESSIONS:
                status = f"duplicate of {DUPLICATE_SESSIONS[s['key']]}"
            elif note is None:
                status = "—"
                missing += 1
            else:
                status = note_status_of(note)
            lines.append(f"| {_cell(s['key'])} | {_cell(s['title'])} | "
                         f"{_cell(s['block'])} | {_cell(status)} |")
        lines.append("")
        counts[pl] = (len(subs), missing)
        total_missing += missing
    lines.append("Counts: " + " · ".join(
        f"{pl} {counts[pl][0]} sessions ({counts[pl][1]} without notes)"
        for pl in PLS))
    lines.append(f"Total: {len(sessions)} sessions | without notes: {total_missing}")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Indexed {len(sessions)} sessions -> {out if out != INVENTORY else 'reference/inventory.md'}")
    print(" | ".join(f"{pl}: {counts[pl][0]} sessions, {counts[pl][1]} without notes"
                     for pl in PLS))
