#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""commands/inventory — moved from _legacy.py (batch helpers now in helpers.py)."""

from __future__ import annotations

try:
    from shelf_core.playlists import PLAYLIST_NAMES, DUPLICATE_SESSIONS, load_sessions
    from shelf_core.notes import find_note, note_status_of, _cell
    from shelf_core.config import INVENTORY
except ImportError:
    from playlists import PLAYLIST_NAMES, DUPLICATE_SESSIONS, load_sessions  # type: ignore
    from notes import find_note, note_status_of, _cell  # type: ignore
    from config import INVENTORY  # type: ignore


def cmd_inventory():
    sessions = load_sessions()
    lines = ["# Shelf inventory (generated — do not hand-edit)", "",
             "> Generated by `python3 tools/shelf.py inventory`. "
             "Note status reads `| Status |` from `reference/<playlist>/notes/`.", ""]
    total_missing = 0
    counts = {}
    for pl in ("cs", "ex", "rr"):
        subs = [s for s in sessions if s["pl"] == pl]
        missing = 0
        lines.append(f"## {pl} — {PLAYLIST_NAMES[pl]}")
        lines.append("")
        lines.append("| Session | Title | Block | Note status |")
        lines.append("| --- | --- | --- | --- |")
        for s in subs:
            note = find_note(s["key"])
            if s["key"] in DUPLICATE_SESSIONS:
                status = f"duplicate of {DUPLICATE_SESSIONS[s['key']]}"
            elif note is None:
                status = "—"
                missing += 1
            else:
                status = note_status_of(note)
            lines.append(f"| {_cell(s['key'])} | {_cell(s['title'])} | "
                         f"{_cell(s['block'])} | {_cell(status)} |")
        lines.append("")
        counts[pl] = (len(subs), missing)
        total_missing += missing
    lines.append("Counts: " + " · ".join(
        f"{pl} {counts[pl][0]} sessions ({counts[pl][1]} without notes)"
        for pl in ("cs", "ex", "rr")))
    lines.append(f"Total: {len(sessions)} sessions | without notes: {total_missing}")
    INVENTORY.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Indexed {len(sessions)} sessions -> reference/inventory.md")
    print(" | ".join(f"{pl}: {counts[pl][0]} sessions, {counts[pl][1]} without notes"
                     for pl in ("cs", "ex", "rr")))
